### ISSUE TITLE
NPE in version 1.1

### ISSUE THREAD

**Issue by michaelpisula** [jenkinsci/regression-report-plugin#4]
Today I had a NPE in my job, after I updated the plugin. Here is the stack trace:
ERROR: Publisher jp.skypencil.jenkins.regression.RegressionReportNotifier aborted due to exception
java.lang.NullPointerException
    at jp.skypencil.jenkins.regression.RegressionReportNotifier.mailReport(RegressionReportNotifier.java:188)
    at jp.skypencil.jenkins.regression.RegressionReportNotifier.perform(RegressionReportNotifier.java:111)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:810)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:785)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:732)
    at hudson.model.Run.execute(Run.java:1568)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:236)

I had a short look into your code, but did not find anything helpful, if you need more info let me know.

Cheers,
Michael

**Comment by sduggisetty** [comment]
I tried setup the Regression Report Plugin for my jenkins build job. But got struck up  with the below error. kindly help.


ERROR: Publisher jp.skypencil.jenkins.regression.RegressionReportNotifier aborted due to exception
java.lang.NoSuchMethodError: hudson.model.AbstractBuild.getTestResultAction()Lhudson/tasks/test/AbstractTestResultAction;


-Subbu

**Comment by KengoTODA** [comment]
@sduggisetty Maybe version of your Jenkins is too new. I'll try to upgrade version of Jenkins core.

**Comment by KengoTODA** [comment]
Maybe we need to release new version which includes d4423fcdc.

**Comment by KengoTODA** [comment]
@sduggisetty 
please try to use version 1.2. If you still have problem, please reopen #5.

**Comment by sduggisetty** [comment]
@KengoTODA 
I am already using version 1.2. 
I don't understand how this plugin works? Do we need to pass any spread sheets as inputs for this?
when i setup this for my job, i see only one option to enter mail ids to send the report.
could you please help me to setup this for a new job..

-Subbu

**Comment by KengoTODA** [comment]
@sduggisetty Make another issue, your problem isn't related with #4.

**Comment by KengoTODA** [comment]
@michaelpisula Hello, are you still using this plugin? If so, please try one of following solutions:

* upgrade your regression-report-plugin to `v1.3`.
* install mailer-plugin and junit-plugin.

I guess that the problem is: this plugin depends on other plugins but its metadata doesn't contain this information. I've solved this problem in `v1.3`.

**Comment by sduggisetty** [comment]
Thank you. I will try the same and confirm.

**Comment by KengoTODA** [comment]
@sduggisetty 
Yes please, but your problem might not be same with his.
