### ISSUE TITLE
regression plugin not triggering

### ISSUE THREAD

**Issue by sduggisetty** [jenkinsci/regression-report-plugin#6]
Hi,

I am trying to use regression-report-plugin plugin for .net application. Using below tools for my build.

Build tool: MS Build
Technology: .Net4.5

I have installed latest version(1.3) too, prior to that i have verified all the dependencies also.

When build is success getting this message- 
"regression reporter doesn't run because build is success."

When build is failure getting this message- 

ERROR: Publisher jp.skypencil.jenkins.regression.RegressionReportNotifier aborted due to exception
java.lang.NoSuchMethodError: hudson.model.AbstractBuild.getTestResultAction()Lhudson/tasks/test/AbstractTestResultAction;
	at jp.skypencil.jenkins.regression.RegressionReportNotifier.perform(RegressionReportNotifier.java:97)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1743)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
---

Could some one please help me on this..

Is this plugin can be used only for java applications? if not, how to use for .net application, please guide me all the details(dependencies..etc).

-Subbu

**Comment by sduggisetty** [comment]
@KengoTODA 

Can we use this plugin for .Net application?

**Comment by KengoTODA** [comment]
@sduggisetty of course.

Could you tell me version of your Jenkins? It might be too old/new.

**Comment by sduggisetty** [comment]
@kengo TODA

I can see the version number as below.

<version>1.609</version>

**Comment by KengoTODA** [comment]
@sduggisetty Thanks for your report!

> java.lang.NoSuchMethodError: hudson.model.AbstractBuild.getTestResultAction()Lhudson/tasks/test/AbstractTestResultAction;
> at jp.skypencil.jenkins.regression.RegressionReportNotifier.perform(RegressionReportNotifier.java:97)

[In version 1.3](https://github.com/jenkinsci/regression-report-plugin/blob/regression-report-plugin-1.3/src/main/java/jp/skypencil/jenkins/regression/RegressionReportNotifier.java), we have no code which calls this method.

So I'm afraid that you haven't upgrade your jenkins plugin to `1.3`, or it still has old version.
Please check which version you're using, and try to restart your jenkins.
